org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

## Mod properties
mod_id=fnfmod
mod_name=Blockified engine
mod_version=2.0.7bbs
mod_group_id=com.fnfmod
mod_authors=Giovanna
mod_description=A feature-full Friday Night Funkin' engine inside of Minecraft. Drop FNF charts and songs into config/fnfmod/songs and play them on the Funkin' Machine block.

## Versions
minecraft_version=1.21.1
neo_version=21.1.235
